selected_list = ['num_pre__OWN_CAR_AGE', 'num_pre__FLAG_MOBIL',
       'num_pre__FLAG_EMP_PHONE', 'num_pre__FLAG_CONT_MOBILE',
       'num_pre__REGION_RATING_CLIENT', 'num_pre__REGION_RATING_CLIENT_W_CITY',
       'num_pre__EXT_SOURCE_1', 'num_pre__BASEMENTAREA_AVG',
       'num_pre__YEARS_BUILD_AVG', 'num_pre__COMMONAREA_AVG',
       'num_pre__ENTRANCES_AVG', 'num_pre__FLOORSMIN_AVG',
       'num_pre__LANDAREA_AVG', 'num_pre__LIVINGAPARTMENTS_AVG',
       'num_pre__NONLIVINGAPARTMENTS_AVG', 'num_pre__NONLIVINGAREA_AVG',
       'num_pre__COMMONAREA_MODE', 'num_pre__LANDAREA_MODE',
       'num_pre__LIVINGAPARTMENTS_MODE', 'num_pre__BASEMENTAREA_MEDI',
       'num_pre__TOTALAREA_MODE', 'num_pre__FLAG_DOCUMENT_3',
       'cat_pre__NAME_CONTRACT_TYPE_Cash loans', 'cat_pre__CODE_GENDER_F',
       'cat_pre__NAME_TYPE_SUITE_Unaccompanied',
       'cat_pre__NAME_INCOME_TYPE_Working',
       'cat_pre__NAME_EDUCATION_TYPE_Secondary / secondary special',
       'cat_pre__NAME_FAMILY_STATUS_Married',
       'cat_pre__NAME_HOUSING_TYPE_House / apartment',
       'cat_pre__HOUSETYPE_MODE_block of flats']
